version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    reviewers:
      - amimart
    assignees:
      - amimart
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - github_actions
